# Generated by Django 5.1.4 on 2024-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='extended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='home_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='python',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='template',
            field=models.IntegerField(default=0),
        ),
    ]
