# Generated by Django 5.1.4 on 2024-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_pagevisit_extended_pagevisit_home_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='home_page_string',
            field=models.IntegerField(default=0),
        ),
    ]
