# Generated by Django 5.1.4 on 2024-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_pagevisit_home_page_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='login',
            field=models.IntegerField(default=0),
        ),
    ]
