# Generated by Django 5.1.4 on 2024-12-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_pagevisit_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='home_page_string',
            new_name='main',
        ),
    ]
